name: flutter_email_sender_example
description: Demonstrates how to use the flutter_email_sender plugin.
publish_to: none

version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  file_selector: ^1.0.3
  flutter_email_sender:
    path: ..
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
